project:
  type: website
  output-dir: docs

website:
  navbar:
    search: true
    background: primary
    left:
      - text: "Shine with quarto"
        href: index.qmd
      - text: "Getting Started"
        menu:
         - text: "R project and basic settings"
           href: R-Project.qmd
         - text: "Deploy on GitHub"
           href: git-hub.qmd
      - text: "Basics"
        menu: 
         - text: "Layout"
           href: html-layout.qmd
         - text: "Code chunk" 
           href: code-chunk.qmd
         - text: "Presentation documents"
           href:  html-presentation.qmd
      - text: "Shiny"
        

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true
    number-sections: true



