project:
  type: website
  output-dir: docs

website:
  sidebar:
    style: "docked"
    search: true
    background: primary
    contents:
      - text: "Shine with quarto"
        href: index.qmd
      - section: "Getting Started"
        contents: 
        - text: R project and basic settings
          href: R-Project.qmd
        - git-hub.qmd
      - text: "Basic documents"
        contents: 
        - html-layout.qmd
        - code-chunk.qmd
      - text: "Presentation documents"
        contents: 
        - html-presentation.qmd
        - shiny-integration.qmd
        

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true



