---
title: "Shine with quarto"
subtitle: "The ARCA initiative: Unlocking psychological expertise for academic and business success"
author: "Ottavia M. Epifania"
execute: 
  echo: false
---
# About the course

This course presents a brief introduction to quarto and shiny. 

[Quarto](https://quarto.org/) is *An open-source scientific and technical publishing system*. 

[Shiny](https://shiny.posit.co/) is an R package that allows for *Easy web apps for data science without the compromises -  No web development skills required*

:::{.callout-tip icon="false"}
## Best thing 

Quarto and Shiny can work with R, Python, Jupyter and other open source softwares. 

Most importantly, shiny and quarto can be integrated, such that it is possible to develop interactive documents :)
:::

## Locations

Lectures will be at Centro Linguistico di Ateneo (CLA), (<https://maps.app.goo.gl/mqMkPLmKKAJitEzZ9>), in **room T2**.

```{r}
library(leaflet)

leaflet() |>
  addTiles() |>
  setView(
    lng = 11.89495,
    lat = 45.41091,
    zoom = 17
  ) |>
  addMarkers(
    lng = 11.89495,
    lat = 45.41091,
    popup = "Centro Linguistico di Ateneo (CLA)<br>Università degli Studi di Padova"
  )
```

Lunch will be served nearby. 


## Time schedule 

Lesson will be on **Thursday 9th** from 9:00 to 17:00 (with a lunch break and some breaks). 

# Download materials 

This [compressed folder](appExamples.zip) contains some basic shiny apps that will be presented in the course.

Two datsets are available [here](data.zip)

